# Form implementation generated from reading ui file 'interface/add_user.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddForm(object):
    def setupUi(self, AddForm):
        AddForm.setObjectName("AddForm")
        AddForm.resize(400, 558)
        AddForm.setStyleSheet("background-color: rgb(255, 255, 255); color:black")
        self.add_pushButton = QtWidgets.QPushButton(parent=AddForm)
        self.add_pushButton.setGeometry(QtCore.QRect(50, 510, 93, 28))
        self.add_pushButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.add_pushButton.setObjectName("add_pushButton")
        self.back_pushButton_2 = QtWidgets.QPushButton(parent=AddForm)
        self.back_pushButton_2.setGeometry(QtCore.QRect(270, 510, 93, 28))
        self.back_pushButton_2.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.back_pushButton_2.setObjectName("back_pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(parent=AddForm)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 331, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.surname_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.surname_lineEdit.setObjectName("surname_lineEdit")
        self.verticalLayout.addWidget(self.surname_lineEdit)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.name_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.verticalLayout.addWidget(self.name_lineEdit)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.email_lineEdit_3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.email_lineEdit_3.setObjectName("email_lineEdit_3")
        self.verticalLayout.addWidget(self.email_lineEdit_3)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.phone_lineEdit_4 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.phone_lineEdit_4.setObjectName("phone_lineEdit_4")
        self.verticalLayout.addWidget(self.phone_lineEdit_4)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.admin_checkBox = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.admin_checkBox.setObjectName("admin_checkBox")
        self.verticalLayout.addWidget(self.admin_checkBox)
        self.emp_checkBox = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.emp_checkBox.setObjectName("emp_checkBox")
        self.verticalLayout.addWidget(self.emp_checkBox)

        self.retranslateUi(AddForm)
        QtCore.QMetaObject.connectSlotsByName(AddForm)

    def retranslateUi(self, AddForm):
        _translate = QtCore.QCoreApplication.translate
        AddForm.setWindowTitle(_translate("AddForm", "Добавить пользователя"))
        self.add_pushButton.setText(_translate("AddForm", "Добавить "))
        self.back_pushButton_2.setText(_translate("AddForm", "Назад"))
        self.label.setText(_translate("AddForm", "Фамилия "))
        self.label_2.setText(_translate("AddForm", "Имя"))
        self.label_3.setText(_translate("AddForm", "Email"))
        self.label_4.setText(_translate("AddForm", "Телефон"))
        self.label_5.setText(_translate("AddForm", "Роль пользователя"))
        self.admin_checkBox.setText(_translate("AddForm", "админ"))
        self.emp_checkBox.setText(_translate("AddForm", "сотрудник"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddForm = QtWidgets.QWidget()
    ui = Ui_AddForm()
    ui.setupUi(AddForm)
    AddForm.show()
    sys.exit(app.exec())
