# Form implementation generated from reading ui file 'interface/autorization.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(437, 303)
        Form.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(150, 20, 151, 31))
        self.label.setObjectName("label")
        self.lineEdit_login = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_login.setGeometry(QtCore.QRect(60, 100, 311, 20))
        self.lineEdit_login.setText("")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(60, 140, 311, 20))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_autorization = QtWidgets.QPushButton(parent=Form)
        self.pushButton_autorization.setGeometry(QtCore.QRect(150, 190, 141, 61))
        self.pushButton_autorization.setObjectName("pushButton_autorization")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Авторизация</span></p></body></html>"))
        self.lineEdit_login.setPlaceholderText(_translate("Form", "введите логин"))
        self.lineEdit_password.setPlaceholderText(_translate("Form", "введите пароль"))
        self.pushButton_autorization.setText(_translate("Form", "войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
