# Form implementation generated from reading ui file 'interface/documents.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(713, 674)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 691, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.cases_tab = QtWidgets.QWidget()
        self.cases_tab.setObjectName("cases_tab")
        self.cases_table = QtWidgets.QTableWidget(parent=self.cases_tab)
        self.cases_table.setGeometry(QtCore.QRect(20, 50, 641, 381))
        self.cases_table.setObjectName("cases_table")
        self.cases_table.setColumnCount(0)
        self.cases_table.setRowCount(0)
        self.status_cb = QtWidgets.QComboBox(parent=self.cases_tab)
        self.status_cb.setGeometry(QtCore.QRect(20, 20, 181, 22))
        self.status_cb.setObjectName("status_cb")
        self.tabWidget.addTab(self.cases_tab, "")
        self.documents_tab = QtWidgets.QWidget()
        self.documents_tab.setObjectName("documents_tab")
        self.doc_tree = QtWidgets.QTreeWidget(parent=self.documents_tab)
        self.doc_tree.setGeometry(QtCore.QRect(10, 10, 661, 351))
        self.doc_tree.setObjectName("doc_tree")
        self.doc_tree.headerItem().setText(0, "1")
        self.load_doc_btn = QtWidgets.QPushButton(parent=self.documents_tab)
        self.load_doc_btn.setGeometry(QtCore.QRect(20, 370, 161, 28))
        self.load_doc_btn.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.load_doc_btn.setObjectName("load_doc_btn")
        self.tabWidget.addTab(self.documents_tab, "")
        self.opici_tab = QtWidgets.QWidget()
        self.opici_tab.setObjectName("opici_tab")
        self.opici_table = QtWidgets.QTableWidget(parent=self.opici_tab)
        self.opici_table.setGeometry(QtCore.QRect(30, 20, 641, 401))
        self.opici_table.setObjectName("opici_table")
        self.opici_table.setColumnCount(0)
        self.opici_table.setRowCount(0)
        self.check_complect_btn = QtWidgets.QPushButton(parent=self.opici_tab)
        self.check_complect_btn.setGeometry(QtCore.QRect(40, 430, 191, 28))
        self.check_complect_btn.setStyleSheet("background-color: rgb(0, 170, 0);\n"
                                        "color: rgb(255, 255, 255);")
        self.check_complect_btn.setObjectName("check_complect_btn")
        self.label = QtWidgets.QLabel(parent=self.opici_tab)
        self.label.setGeometry(QtCore.QRect(540, 430, 141, 16))
        self.label.setObjectName("label")
        self.status_check_label = QtWidgets.QLabel(parent=self.opici_tab)
        self.status_check_label.setGeometry(QtCore.QRect(540, 450, 121, 51))
        self.status_check_label.setText("")
        self.status_check_label.setObjectName("status_check_label")
        self.tabWidget.addTab(self.opici_tab, "")
        self.back_pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.back_pushButton_2.setGeometry(QtCore.QRect(270, 510, 93, 28))
        self.back_pushButton_2.setStyleSheet("background-color: rgb(0, 170, 0);\n"
                                             "color: rgb(255, 255, 255);")
        self.back_pushButton_2.setObjectName("back_pushButton_2")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cases_tab), _translate("Form", "Электронные дела"))
        self.load_doc_btn.setText(_translate("Form", "Загрузить документ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documents_tab), _translate("Form", "Документы"))
        self.check_complect_btn.setText(_translate("Form", "проверить комплектность"))
        self.label.setText(_translate("Form", "Статус проверки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.opici_tab), _translate("Form", "Описи"))
        self.back_pushButton_2.setText(_translate("Form", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
