# Form implementation generated from reading ui file 'interface/request.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UpdateReqForm(object):
    def setupUi(self, UpdateReqForm):
        UpdateReqForm.setObjectName("UpdateReqForm")
        UpdateReqForm.resize(379, 449)
        UpdateReqForm.setStyleSheet("background-color: rgb(255, 255, 255); color:black")
        self.update_pushButton = QtWidgets.QPushButton(parent=UpdateReqForm)
        self.update_pushButton.setGeometry(QtCore.QRect(40, 390, 93, 28))
        self.update_pushButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.update_pushButton.setObjectName("update_pushButton")
        self.back_pushButton_2 = QtWidgets.QPushButton(parent=UpdateReqForm)
        self.back_pushButton_2.setGeometry(QtCore.QRect(260, 390, 93, 28))
        self.back_pushButton_2.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.back_pushButton_2.setObjectName("back_pushButton_2")
        self.delete_pushButton_2 = QtWidgets.QPushButton(parent=UpdateReqForm)
        self.delete_pushButton_2.setGeometry(QtCore.QRect(150, 390, 93, 28))
        self.delete_pushButton_2.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.delete_pushButton_2.setObjectName("delete_pushButton_2")
        self.widget = QtWidgets.QWidget(parent=UpdateReqForm)
        self.widget.setGeometry(QtCore.QRect(40, 20, 301, 351))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.num_req_label_2 = QtWidgets.QLabel(parent=self.widget)
        self.num_req_label_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.num_req_label_2.setText("")
        self.num_req_label_2.setObjectName("num_req_label_2")
        self.verticalLayout.addWidget(self.num_req_label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.date_req_label_4 = QtWidgets.QLabel(parent=self.widget)
        self.date_req_label_4.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.date_req_label_4.setText("")
        self.date_req_label_4.setObjectName("date_req_label_4")
        self.verticalLayout.addWidget(self.date_req_label_4)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.status_comboBox = QtWidgets.QComboBox(parent=self.widget)
        self.status_comboBox.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.status_comboBox.setObjectName("status_comboBox")
        self.verticalLayout.addWidget(self.status_comboBox)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.priority_comboBox_2 = QtWidgets.QComboBox(parent=self.widget)
        self.priority_comboBox_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.priority_comboBox_2.setObjectName("priority_comboBox_2")
        self.verticalLayout.addWidget(self.priority_comboBox_2)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.type_req_comboBox_3 = QtWidgets.QComboBox(parent=self.widget)
        self.type_req_comboBox_3.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.type_req_comboBox_3.setObjectName("type_req_comboBox_3")
        self.verticalLayout.addWidget(self.type_req_comboBox_3)

        self.retranslateUi(UpdateReqForm)
        QtCore.QMetaObject.connectSlotsByName(UpdateReqForm)

    def retranslateUi(self, UpdateReqForm):
        _translate = QtCore.QCoreApplication.translate
        UpdateReqForm.setWindowTitle(_translate("UpdateReqForm", "Заявка"))
        self.update_pushButton.setText(_translate("UpdateReqForm", "Обновить"))
        self.back_pushButton_2.setText(_translate("UpdateReqForm", "Назад"))
        self.delete_pushButton_2.setText(_translate("UpdateReqForm", "Удалить"))
        self.label.setText(_translate("UpdateReqForm", "номер заявки"))
        self.label_3.setText(_translate("UpdateReqForm", "дата создания"))
        self.label_4.setText(_translate("UpdateReqForm", "статус"))
        self.label_2.setText(_translate("UpdateReqForm", "приоритет заявки"))
        self.label_5.setText(_translate("UpdateReqForm", "тип заявки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdateReqForm = QtWidgets.QWidget()
    ui = Ui_UpdateReqForm()
    ui.setupUi(UpdateReqForm)
    UpdateReqForm.show()
    sys.exit(app.exec())
